name: E2E Tests

on:
  push:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      # Lance ton app en arrière-plan
      - name: Start app
        run: npm start &

      # Attend que l'app soit prête
      - name: Wait for app
        run: npx wait-on http://127.0.0.1:8080

      # Lance Cypress
      - name: Run Cypress
        run: npx cypress run

      # Debug : liste les fichiers générés
      - name: List Cypress files
        if: always()
        run: |
          ls -R cypress/screenshots || true
          ls -R cypress/videos || true

      # Upload screenshots
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      # Upload vidéos
      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore